### PR TITLE
Add pt-PT localization and rename previous pt to pt_BR

### PR DESCRIPTION
**Pull request by hmiguim**
Added the Portuguese (Portugal) localization and rename the previous one to pt_BR

### CODE REVIEW

**Comment by voidburn** [comment]
Hi Miguel, you should update the tests for pt_BR so that they can correctly load their variant, and please add tests for pt_PT. 

This is going to be a breaking change for users that previously used the Portuguese localization so it needs to have good coverage and documentation. Also please edit the README section to include pt_PT in the list and list yourself as the author.

When this is done I'll merge,

Thanks!

**Comment by hmiguim** [comment]
I forgot to run the tests, sorry. I made the changes requested.

**Comment by voidburn** [comment]
Fantastic, thanks! 

Will review, merge and push out a new version soon!

**Comment by voidburn** [comment]
All done, 1.2.5 should be up in maven in an hour or so. Please note that I've changed the localization string to `pt` for Portuguese, instead of `pt-PT`.

Thank you for your contribution!

**Pull request merged**
